services:
  mysql:
    image: mysql:8.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: graphql_sample
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql/initdb.d:/docker-entrypoint-initdb.d
